### ISSUE TITLE
Update this repo's description

### ISSUE THREAD

**Issue by ghost** [Kong/kong-plugin-liamp#10]
Suggestion: change from "Extended AWS Lambda plugin" to "Invoke an [AWS Lambda](https://aws.amazon.com/lambda/) function from Kong".

**Comment by Tieske** [comment]
@RobSerafini you've got the Github super-powers to do this right? at least the "Extended" part is a remnant of the "liamp" plugin and should now be removed since that was merged.

**Comment by Tieske** [comment]
Ping @RobSerafini

**Comment by Tieske** [comment]
Ping @RobSerafini
