### ISSUE TITLE
Getting close error while invoking the lambda

### ISSUE THREAD

**Issue by ashish2007csGit** [Kong/kong-plugin-liamp#13]
Hi Team,
I am getting a very critical issue in the lambda plugin while connection to lambda from kong. 
below is error 
handler.lua:188 [-aws-lambda] closed,  client: 10.0.0.0. , server: kong, request: "GET /apis HTTP/1.1", host: "*.com"

**Comment by Tieske** [comment]
related Kong issue: https://github.com/Kong/kong/issues/5246

keeping this open, but locking it, so post any updates in referenced issue.

**Comment by gszr** [comment]
Since this repo was merged with https://github.com/Kong/kong, I'm closing this issue; let's continue the discussion in https://github.com/Kong/kong/issues/5246.
