### ISSUE TITLE
Schema in this repo does not match schema exposed at /plugins/schema/aws-lambda

### ISSUE THREAD

**Issue by travisreed** [Kong/kong-plugin-liamp#17]
## Summary
I am using Kong Community Edition 1.4.0 and trying to use the aws-lambda plugin for the first time. When I try to enable the plugin on a service without a aws_key or aws_secret I get a schema violation error.

## Details
I have kong deployed on an ec2 instance with an iam role/instance profile that allows it to invoke a lambda.

When I make this request to the kong admin api 

```python
data = {
     "name": "aws-lambda",
     "service": {
         "name": "travis-j-reed-kong-test"
     },
     "config": {
        "aws_region": "us-east-1",
         "function_name": "travis-j-reed-kong-test"
     }
}
url = <kong_admin_url>/services/<service_id>/plugins'
r = requests.post(url, json=data)
```
I get the following response

```
b'{"message":"2 schema violations (config.aws_key: required field missing; config.aws_secret: required field missing)","name":"schema violation","fields":{"config":{"aws_key":"required field missing","aws_secret":"required field missing"}},"code":2}'
```

To debug further, I hit the /plugins/schema/aws-lambda endpoint and get this response:
<details>
   <Summary>Response</Summary><pre>{
  "fields": [
    {
      "timeout": {
        "type": "number",
        "default": 60000,
        "required": true
      }
    },
    {
      "keepalive": {
        "type": "number",
        "default": 60000,
        "required": true
      }
    },
    {
      "aws_key": {
        "required": true,
        "type": "string"
      }
    },
    {
      "aws_secret": {
        "required": true,
        "type": "string"
      }
    },
    {
      "aws_region": {
        "one_of": [
          "ap-northeast-1",
          "ap-northeast-2",
          "ap-south-1",
          "ap-southeast-1",
          "ap-southeast-2",
          "ca-central-1",
          "cn-north-1",
          "cn-northwest-1",
          "eu-central-1",
          "eu-west-1",
          "eu-west-2",
          "sa-east-1",
          "us-east-1",
          "us-east-2",
          "us-gov-west-1",
          "us-west-1",
          "us-west-2"
        ],
        "type": "string",
        "required": true
      }
    },
    {
      "function_name": {
        "required": true,
        "type": "string"
      }
    },
    {
      "qualifier": {
        "type": "string"
      }
    },
    {
      "invocation_type": {
        "type": "string",
        "one_of": [
          "RequestResponse",
          "Event",
          "DryRun"
        ],
        "default": "RequestResponse",
        "required": true
      }
    },
    {
      "log_type": {
        "type": "string",
        "one_of": [
          "Tail",
          "None"
        ],
        "default": "Tail",
        "required": true
      }
    },
    {
      "port": {
        "between": [
          0,
          65535
        ],
        "default": 443,
        "type": "integer"
      }
    },
    {
      "unhandled_status": {
        "between": [
          100,
          999
        ],
        "type": "integer"
      }
    },
    {
      "forward_request_method": {
        "default": false,
        "type": "boolean"
      }
    },
    {
      "forward_request_uri": {
        "default": false,
        "type": "boolean"
      }
    },
    {
      "forward_request_headers": {
        "default": false,
        "type": "boolean"
      }
    },
    {
      "forward_request_body": {
        "default": false,
        "type": "boolean"
      }
    },
    {
      "is_proxy_integration": {
        "default": false,
        "type": "boolean"
      }
    }
  ]
}
</details>

In order to eliminate issues with my installation of kong I followed these instructions to install kong locally and was able to reproduce the schema response.
https://docs.konghq.com/install/docker/

Is there something that I need to do to update to the latest version of this plugin?

Thank you in advance for any help you are able to provide!

**Comment by Tieske** [comment]
Kong 1.4 shipped with the old version of the plugin. The new 2.0 RC has the new plugin (this one)

**Comment by tzifudzi** [comment]
@Tieske if I want to use the new plugin will I have to update Kong? I am still running on Kong 1.5x and am facing the same issue.

**Comment by Tieske** [comment]
@tzifudzi you can try and replace the lambda plugin version in your Kong version with a newer one, by removing it, and then reinstall from this repo. Probably best to first check the changelog for the changes made... mileage may vary...

**Comment by tzifudzi** [comment]
Thanks for the suggestion @Tieske. I managed to install it on Kong 1.5.x and I can confirm that it is compatible.

**Comment by Tieske** [comment]
@tzifudzi thx for reporting back!
