### ISSUE TITLE
support for lambda running in local machines (development)

### ISSUE THREAD

**Issue by zvictor** [Kong/kong-plugin-liamp#26]
Firstly, thank you for the great work with Kong and this plugin!

I am trying to use it as a gateway for my lambda functions, which in development I run in my own machine using [lambci/docker-lambda](https://github.com/lambci/docker-lambda#usage).

I noticed that kong-plugin-aws-lambda has no support for any lambda-compatible service other than the ones at AWS, so I would like to ask if there is any known workaround.

I can see in the codebase that the requests to AWS are hardcoded and not configurable:
https://github.com/Kong/kong-plugin-aws-lambda/blob/303e3869955b42da013fcff57bbd97a2adb4abeb/kong/plugins/aws-lambda/handler.lua#L166

I tried proxying the requests and rerouting calls from docker to the aws domain, but I failed on doing so. I always get an error at:

https://github.com/Kong/kong-plugin-aws-lambda/blob/303e3869955b42da013fcff57bbd97a2adb4abeb/kong/plugins/aws-lambda/handler.lua#L213-L217

> [error] 26#0: *589 [kong] iam-ec2-credentials.lua:89 [aws-lambda] Could not connect to metadata service: timeout, client: 172.17.0.1, server: kong, request: "GET /myfunction HTTP/1.1", host: "localhost:8000"
172.17.0.1 - - [29/Feb/2020:11:24:47 +0000] "GET /myfunction HTTP/1.1" 500 42 "-" "curl/7.64.1"

**Comment by Tieske** [comment]
the hostnames are hardcoded indeed.

The second error seems to be related to the IAM credentials, if you haven't set the credentials in the plugin configuration, then it will try to get the credentials from the IAM metadata-service, looks like that fails.

Is the aws clone also compatible with the metadata service of AWS? does it work if you provide credentials in the plugin configuration?

**Comment by gszr** [comment]
Hi @zvictor, version 3.4.0 has just [been released](https://github.com/Kong/kong-plugin-aws-lambda/releases/tag/3.4.0) and includes this feature. Please give it a try! 🦍
