### ISSUE TITLE
Any request over 10.5k returns a null body to the lambda

### ISSUE THREAD

**Issue by djha-skin** [Kong/kong-plugin-liamp#45]
We have observed that any time a request is sent through Kong to our lambda with a body size larger than 10753 bytes, the request body field given to our lambda comes up as `null`, regardless of whether or not `skip_large_bodies` was specified as `true`.

I am not sure why the number is 10.5k, nor why it is so reproducible, but it's *close* to the default `nginx_http_client_body_buffer_size` of 8k, so I figure they're related. Further, since the `skip_large_bodies` flag makes no difference in whether or not we actually receive the body back when we process the data in our lambda, it leads me to believe that [this line of code in the AWS lambda plugin](https://github.com/Kong/kong-plugin-aws-lambda/blob/master/kong/plugins/aws-lambda/request-util.lua#L9) returns null every time when a request gets to be too big. This makes sense because if it returns null, skip_large_bodies is completely ignored and results in nothing being different. It also results in a null body.

Again, the 10.5k thing is baffling, but I see no way of fixing this by changing any particular kong setting (other than perhaps `nginx_http_client_body_buffer_size`, but I am concerned about performance and hope I don't end up having to change it  much).

Please help?

To give more background or to be perfectly clear: our set-up is a hybrid-mode enterprise deployment with the control plane nodes deployed to their own ECS cluster and data plane nodes also being run in a containerized environment elsewhere. There is an AWS lambda that is processing requests coming in for a particular route. If the request size is too big, the request body given in the json object to the lambda is null, every time, regardless of `skip_large_bodies`.

**Comment by djha-skin** [comment]
Wanted to add some more information. By increasing the size of `nginx_http_client_body_buffer_size`, my dev was able to get a body size of ~1MB through, so the setting does have bearing on what's happening. Further, he still confirms that the `skip_large_bodies` setting seems to have no effect, confirming my suspicions that the plugin is not able to retrieve larger streamed bodies from disk.

**Comment by djha-skin** [comment]
More information. All of this comment is in regard to the bug found on line 9 in this file: https://github.com/Kong/kong-plugin-aws-lambda/blob/master/kong/plugins/aws-lambda/request-util.lua#L9


The problem, as I understand it, is that before calling `ngx.req.get_body_file()` in that file, the function `ngx.req.read_body()` should be called first, but it isn't. Source: https://openresty-reference.readthedocs.io/en/latest/Lua_Nginx_API/?q=get_body_file&check_keywords=yes&area=default#ngxreqget_body_file

In order to get around this bug in the plugin, we were able to set the not-recommended setting of `lua_need_request_body` by setting `KONG_NGINX_HTTP_LUA_NEED_REQUEST_BODY` on the dataplane deployment. This got us to a better place of being able to observe the error message in the logs printed on line 12 of that file.

However, we believe that #44 is not yet fixed, and we have commented on that ticket showing that the line that originally caused the breakage in #44 hasn't been fixed yet. We were also able to prove experimentally that:

  - Kong WAS picking up our lambda config, since we specified the non-default value of `true` for `forward_request_body` and this was honored
  - However, Kong lambda plugin was NOT honoring the `skip_large_bodies` configuration item.

I think, in order to fix this issue, the following needs to be done:

- A call to `ngx.req.read_body()` needs to be added before the `ngx.req.get_body_file()` call
- `skip_large_bodies` needs to be honored by fixing the logic in aws-serializer.lua (here: https://github.com/Kong/kong-plugin-aws-lambda/blob/master/kong/plugins/aws-lambda/aws-serializer.lua#L57) so that skip_large_bodies is honored.

If that aws-serialize.lua line is not the bug, then i'm telling you, the bug is *somewhere*. That configuration item is simply not being honored, no matter what we do, even though other configuration items like `forward_request_body` *are* being honored.

Please fix, thank you.

**Comment by billb1422** [comment]
We desperately need this fixed please. Thank you.

**Comment by verisk-dhaskin** [comment]
I created a pull request (#48). I have tested and verified that that pull request fixes our issue. I hope that it is accepted; please message me if you have any problems with it.

**Comment by Tieske** [comment]
fixed by #48
