### ISSUE TITLE
Making Plugin Priority Configurable

### ISSUE THREAD

**Issue by brycehemme** [Kong/kong-plugin-liamp#46]
There are a number of use cases in which making the priority of a plugin configurable would be valuable, including the order of different auth and security related plugins. Would a PR that makes this change for this plugin be accepted? Thanks!

Note, [this issue](https://github.com/Kong/kong/issues/267) speaks to the need.

**Comment by Tieske** [comment]
This is something that is inherent to Kong's core. Very complex to change. I commented on the other issue with a workaround. Closing it here.
