### ISSUE TITLE
multiValueHeaders is not returned in response

### ISSUE THREAD

**Issue by CYWong-Nick** [Kong/kong-plugin-liamp#53]
This function only handles header but not multiValueHeaders of the response. It does not seem to be intentional since multiValueHeaders is handled in request. 

https://github.com/Kong/kong-plugin-aws-lambda/blob/master/kong/plugins/aws-lambda/handler.lua#L86

Many of the standard HTTP headers are multi-valued (Accept, CORS headers...) and therefore should be respected by the plugin.

**Comment by Tieske** [comment]
can you be more specific? that method just copies the headers into a headers table?

What is the input, what is the output observed, and what is the output expected?

**Comment by CYWong-Nick** [comment]
**Result from AWS Lambda**

```
{
	"headers": {
		"Age": "3600"
	},
	"multiValueHeaders": {
		"Access-Control-Allow-Origin": ["site1.com", "site2.com"]
	}
}
```
-------------------

**Actual result:**

Headers(Age=3600)

-------------------

**Expected behavior:**

Headers(Age=3600;Access-Control-Allow-Origin=site1.com,site2.com;)

-------------------

As you can see from the case, **multiValueHeaders** is not copied to the output, but it should also be part of the response.
